alias gs='git status'
alias gl='git log --oneline --graph --all'
alias ga='git add'
alias gc='git commit'
alias gca='git commit -am'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gpush='git push'
alias gpull='git pull'
alias gst='git stash'
alias gsp='git stash pop'
alias gsl='git stash list'
alias gdf='git diff'
alias gdc='git diff --cached'
alias grh='git reset HEAD'

alias ..='cd ..'
alias ...='cd ../..'
alias home='cd ~'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias nv='nvim'

alias ni='npm install'
alias ns='npm start'
alias nr='npm run'
